---
- hosts: all
  become: true
  tasks:
    - name: ensure rsyslog is installed on all machines
      dnf:
        name: rsyslog
        state: present

    - name: Add mappings to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      loop:
        - { name: webserver1, ip: 192.168.56.197 }
        - { name: webserver2, ip: 192.168.56.193 }
        - { name: webserver3, ip: 192.168.56.192 }
        - { name: haproxylb1, ip: 192.168.56.199 }
        - { name: haproxylb2, ip: 192.168.56.198 }

    - name: All servers should have EPEL
      dnf:
        name: epel-release
        state: present

    - name: Checking for SELINUX enforcing
      lineinfile:
        path: /etc/selinux/config
        regex: '^SELINUX=enforcing'
        line: 'SELINUX=disabled'
      notify: reboot server
  handlers:
    - name: reboot server
      command: reboot

- hosts: web
  become: True
  tasks:
    - name: Install Web Servers
      dnf:
        name: httpd
        state: present
    
    - name: Start our web services
      systemd:
        name: httpd
        state: started
        enabled: yes


    - name: Copy web content
      template:
        src: templates/{{ ansible_hostname }}.j2
        dest: /var/www/html/index.html
    
    - name: Enusre firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open ports for http and https
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: true
      loop:
        - 80/tcp
        - 22/tcp
        - 443/tcp

          ##Haproxy Section

- hosts: lb
  become: true
  tasks:
    - name: Install keepalived
      dnf:
        name: keepalived
        state: present
    
    - name: Starting the keepalived service
      systemd:
        name: keepalived
        state: started
        enabled: yes
    
    - name: KeepaliveD configuration
      template:
        src: templates/keepalived.{{ ansible_hostname }}.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

    - name: Install haproxy
      dnf:
        name: haproxy
        state: present

    - name: Enusre firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open ports for http and https
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: true
      loop:
        - 80/tcp
        - 22/tcp
        - 443/tcp
   
    - name: Copy updated SSL certificate
      copy:
        src: templates/certs/stockcheckerapp.com.pem
        dest: /etc/pki/tls/certs/stockcheckerapp.com.pem
        owner: root
        group: root
        mode: '0777'
      tags: copyssl
 
    - name: Ensure haproxy is configured
      template:
        src: templates/haproxy.j2
        dest:  /etc/haproxy/haproxy.cfg
      notify: restart haproxy
      tags: haproxyconfig
      
    - name: Start haproxy service
      systemd:
        name: haproxy
        state: started
        enabled: yes

    - name: create logging directory for haproxy
      file:
        path: /var/lib/haproxy/dev
        state: directory
        mode: '0755'
      notify: restart haproxy
     
    - name:  create rsyslog for haproxy logs
      template:
        src: templates/haproxyrsyslog.j2
        dest: /etc/rsyslog.d/99-haproxy.conf
      notify: restart rsyslog

  handlers:
    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted

    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted
    - name: restart keepalived
      systemd:
        name: keepalived
        state: restarted
          #- name: Make sure our SSL certs are inplace for https traffic
